# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
notifications:
  email: false
os:
  - linux
  - osx
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
julia:
  - 1.6.2
  - nightly
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  include:
    - stage: Documentation
      julia: 1
      script: |
        julia --project=docs -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          using Documenter: DocMeta, doctest
          using Token
          DocMeta.setdocmeta!(Token, :DocTestSetup, :(using Token); recursive=true)
          doctest(Token)
          include("docs/make.jl")'
      after_success: skip
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
