name = "Tokens"
uuid = "bee08b60-e23d-11e9-3bd0-1baccf3efd5c"
authors = ["Robert Rudolph"]
version = "0.1.0"

[deps]
MurmurHash3 = "b10b62ed-fbae-5ea5-b934-abaf0477b71d"

[compat]
MurmurHash3 = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
