name = "Tokens"
uuid = "bee08b60-e23d-11e9-3bd0-1baccf3efd5c"
authors = ["Robert Rudolph"]
version = "0.1.0"

[deps]
MurmurHash3 = "b10b62ed-fbae-5ea5-b934-abaf0477b71d"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
